version: '3.8'
services:
  web:
    container_name: django-web
    build: .
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env
    ports:
      - 8000:8000

networks:
  django-task: